MVCApplicationCore/MVCApplicationCore/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApplicationCore.Services.Contract;
using MVCApplicationCore.ViewModels;

namespace MVCApplicationCore.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel register)
        {
            if (ModelState.IsValid)
            {
                var message = _authService.RegisterUserService(register);
                if (!string.IsNullOrWhiteSpace(message))
                {
                    TempData["ErrorMessage"] = message;
                    return View(register);
                }

                return RedirectToAction("RegisterSuccess");
            }

            return View(register);
        }

        public IActionResult RegisterSuccess()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel login)
        {
            if (ModelState.IsValid)
            {
                var message = _authService.LoginUserService(login);
                if (message == "Invalid username or password!")
                {
                    TempData["ErrorMessage"] = message;
                    return View(login);
                }
                else if (message == "Something went wrong, please try after sometime.")
                {
                    TempData["ErrorMessage"] = message;
                    return View(login);
                }
                else
                {
                    string token = message;
                    Response.Cookies.Append("jwtToken", token, new CookieOptions
                    {
                        HttpOnly = true,
                        Secure = true,
                        SameSite = SameSiteMode.Strict
                    });

                    return RedirectToAction("Index", "Category");
                }
            }

            return View(login);
        }

        public IActionResult Logout()
        {
            Response.Cookies.Delete("jwtToken");

            return RedirectToAction("Index", "Home");
        }
    }
}

MVCApplicationCore/MVCApplicationCore/Controllers/CategoryMVC5Controller.cs
using Microsoft.AspNetCore.Mvc;
using MVCApplicationCore.Models;

namespace MVCApplicationCore.Controllers
{
    public class CategoryMVC5Controller : Controller
    {
        private static List<Category> _categories = new List<Category>
        {
            new Category{ CategoryId=1, Name="Category 1", Description="Description 1" },
            new Category{ CategoryId=2, Name="Category 2", Description="Description 2" },
        };
        public IActionResult Index()
        {
            return View(_categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                category.CategoryId = _categories.Count() + 1;
                _categories.Add(category);
                return RedirectToAction("Index");
            }

            return View(category);
        }

        public IActionResult Edit(int id)
        {
            var category = _categories.Find(c => c.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                var existingCategory = _categories.Find(c => c.CategoryId == category.CategoryId);
                if (existingCategory != null)
                {
                    existingCategory.Name = category.Name;
                    existingCategory.Description = category.Description;
                    return RedirectToAction("Index");
                }
            }

            return View(category);

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var category = _categories.Find(c => c.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int categoryId)
        {
            var category = _categories.Find(c => c.CategoryId == categoryId);
            if (category != null)
            {
                _categories.Remove(category);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var category = _categories.Find(c => c.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
    }
}

MVCApplicationCore/MVCApplicationCore/Controllers/MyLayoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCApplicationCore.Controllers
{
    public class MyLayoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCApplicationCore/MVCApplicationCore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApplicationCore.Models;
using MVCApplicationCore.Services.Contract;
using MVCApplicationCore.ViewModels;

namespace MVCApplicationCore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var products = _productService.GetAllProducts();
            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Categories = new List<Models.Category>();
            productViewModel.Categories = _categoryService.GetCategories().ToList();
            return View(productViewModel);
        }

        [HttpPost]
        public IActionResult Create(ProductViewModel productviewModel)
        {
            if (ModelState.IsValid)
            {
                var product = new Product()
                {
                    CategoryId = productviewModel.CategoryId,
                    ProductName = productviewModel.ProductName,
                    ProductDescription = productviewModel.ProductDescription,
                    ProductPrice = productviewModel.ProductPrice,
                    InStock = productviewModel.InStock,
                    IsActive = productviewModel.IsActive,
                };

                var message = _productService.AddProduct(product);
                if (!string.IsNullOrWhiteSpace(message))
                {
                    if (message == "Something went wrong. Please try after sometime." || message == "Product already exists.")
                    {
                        TempData["ErrorMessage"] = message;
                    }
                    else
                    {
                        TempData["SuccessMessage"] = message;
                        return RedirectToAction("Index");
                    }
                }
            }
            productviewModel.Categories = new List<Models.Category>();
            productviewModel.Categories = _categoryService.GetCategories().ToList();
            return View(productviewModel);
        }
    }
}

MVCApplicationCore/MVCApplicationCore/Views/Shared/_AuthenticationPartialView.cshtml
@if (!User.Identity.IsAuthenticated)
{
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" asp-action="Register" asp-controller="Auth"><span class="fas fa-user"> Sign Up</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="Login" asp-controller="Auth"><span class="fas fa-sign-in-alt"> Sign In</span></a>
        </li>
    </ul>
}
else
{

    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="#" ><span class="fas fa-user"> @User.Identity.Name </span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="Logout" asp-controller="Auth"><span class="fas fa-sign-in-alt"> Sign Out</span></a>
        </li>
    </ul>
}

MVCApplicationCore/MVCApplicationCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApplicationCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApplicationCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @Html.Partial("_MenubarPartialView")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @{
                var successMessage = TempData["SuccessMessage"]?.ToString();
                var errorMessage = TempData["ErrorMessage"]?.ToString();
            }
            @if (!string.IsNullOrWhiteSpace(successMessage))
            {
                <div id="autoCloseAlert" class="alert alert-success alert-dismissible fade show">
                    <b>Success:</b> @successMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            @if (!string.IsNullOrWhiteSpace(errorMessage))
            {
                <div id="autoCloseAlert" class="alert alert-danger alert-dismissible fade show">
                    <b>Error:</b> @errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCApplicationCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        setTimeout(function () {
            document.getElementById('autoCloseAlert').classList.add('fade');
            document.getElementById('autoCloseAlert').classList.add('show');
            document.getElementById('autoCloseAlert').style.display = 'none';
        }, 5000) // 5000 milliseconds = 5 seconds
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCApplicationCore/MVCApplicationCore/Views/Shared/_MenubarPartialView.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCApplicationCore</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="CategoryMVC5" asp-action="Index">Category MVC5</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="categories" asp-action="">Category Attribute Routing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="MyLayout" asp-action="Index">Layout Example</a>
                </li>
            </ul>
            <partial name="_AuthenticationPartialView" />
        </div>
    </div>
</nav>

MVCApplicationCore/MVCApplicationCore/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    @* <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title> *@
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApplicationCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApplicationCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @Html.Partial("_MyLayoutMenuPartial")
    </header>
    <div class="container">
        <h1>Using My Layout</h1>
        <main role="main" class="pb-3">
            @{
                var successMessage = TempData["SuccessMessage"]?.ToString();
                var errorMessage = TempData["ErrorMessage"]?.ToString();
            }
            @if (!string.IsNullOrWhiteSpace(successMessage))
            {
                <div id="autoCloseAlert" class="alert alert-success alert-dismissible fade show">
                    <b>Success:</b> @successMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            @if (!string.IsNullOrWhiteSpace(errorMessage))
            {
                <div id="autoCloseAlert" class="alert alert-danger alert-dismissible fade show">
                    <b>Error:</b> @errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCApplicationCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        setTimeout(function () {
            document.getElementById('autoCloseAlert').classList.add('fade');
            document.getElementById('autoCloseAlert').classList.add('show');
            document.getElementById('autoCloseAlert').style.display = 'none';
        }, 5000) // 5000 milliseconds = 5 seconds
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCApplicationCore/MVCApplicationCore/Views/Shared/_MyLayoutMenuPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCApplicationCore</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="transferdata" asp-action="viewbagexample">ViewBag Example</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="transferdata" asp-action="viewdata">ViewData Example</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="transferdata" asp-action="viewdatatypecasting">ViewData Type Casting Example</a>
                </li>
            </ul>
            <partial name="_AuthenticationPartialView" />
        </div>
    </div>
</nav>